-- GiftPep security/finance migration
-- Run once in Supabase SQL Editor BEFORE deploying the patched server.js.

create extension if not exists pgcrypto;

-- Core tables that older builds sometimes replaced with in-memory fallbacks.
create table if not exists public.user_gifts (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  gift_id text not null,
  gift_name text not null,
  gift_price numeric not null default 0,
  gift_image text not null default '',
  withdraw_available_at timestamptz,
  tg_msg_id bigint,
  tg_slug text,
  tg_is_unique boolean,
  created_at timestamptz not null default now()
);
create index if not exists user_gifts_user_created_idx on public.user_gifts(user_id, created_at desc);

create table if not exists public.user_pending_prizes (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  gift_id text not null,
  gift_name text not null,
  gift_price numeric not null default 0,
  gift_image text not null default '',
  created_at timestamptz not null default now()
);
-- Keep the newest pending prize if an old build accidentally left duplicates.
with ranked as (
  select ctid, row_number() over (partition by user_id order by created_at desc nulls last, ctid desc) as rn
  from public.user_pending_prizes
)
delete from public.user_pending_prizes p using ranked r where p.ctid=r.ctid and r.rn>1;
create unique index if not exists user_pending_prizes_user_uq on public.user_pending_prizes(user_id);

create table if not exists public.tg_username_links (
  username text not null,
  user_id bigint not null,
  updated_at timestamptz not null default now()
);
-- Old rows are safe to collapse to the most recently updated mapping; signed initData refreshes ownership.
with ranked as (
  select ctid, row_number() over (partition by lower(username) order by updated_at desc nulls last, ctid desc) as rn
  from public.tg_username_links
)
delete from public.tg_username_links p using ranked r where p.ctid=r.ctid and r.rn>1;
update public.tg_username_links set username=lower(regexp_replace(trim(username), '^@', ''));
with ranked as (
  select ctid, row_number() over (partition by user_id order by updated_at desc nulls last, ctid desc) as rn
  from public.tg_username_links
)
delete from public.tg_username_links p using ranked r where p.ctid=r.ctid and r.rn>1;

-- Bring older GiftPep schemas up to the columns required by the hardened backend.
alter table public.user_gifts add column if not exists withdraw_available_at timestamptz;
alter table public.user_gifts add column if not exists tg_msg_id bigint;
alter table public.user_gifts add column if not exists tg_slug text;
alter table public.user_gifts add column if not exists tg_is_unique boolean;
create unique index if not exists user_gifts_tg_msg_id_uq
  on public.user_gifts(tg_msg_id) where tg_msg_id is not null;
create unique index if not exists user_gifts_tg_slug_uq
  on public.user_gifts(tg_slug) where tg_slug is not null;

-- One Telegram username must map to one signed Telegram user, and one user has one current username.
create unique index if not exists tg_username_links_username_uq on public.tg_username_links(username);
create unique index if not exists tg_username_links_user_id_uq on public.tg_username_links(user_id);

-- Promo storage used by the admin panel. Public hardcoded promo codes are intentionally removed.
create table if not exists public.promo_codes (
  code text primary key,
  reward numeric not null default 0,
  max_uses_per_user integer not null default 1,
  active boolean not null default true,
  reward_gift_id text
);
create table if not exists public.manual_promo_redemptions (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  code text not null,
  redeemed_at timestamptz not null default now()
);
create index if not exists manual_promo_redemptions_user_code_idx
  on public.manual_promo_redemptions(user_id, code, redeemed_at desc);

create table if not exists public.payment_receipts (
  telegram_charge_id text primary key,
  provider_charge_id text,
  invoice_id uuid,
  withdraw_intent_id uuid,
  user_id bigint not null,
  kind text not null check (kind in ('deposit','withdraw')),
  amount integer not null check (amount > 0),
  currency text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.payment_receipts add column if not exists withdraw_intent_id uuid;
create unique index if not exists payment_receipts_invoice_id_uq
  on public.payment_receipts(invoice_id) where invoice_id is not null and kind = 'deposit';
create unique index if not exists payment_receipts_withdraw_intent_id_uq
  on public.payment_receipts(withdraw_intent_id) where withdraw_intent_id is not null and kind = 'withdraw';

create table if not exists public.withdraw_intents (
  id uuid primary key,
  user_id bigint not null,
  gift_db_id bigint not null,
  fee_stars integer not null check (fee_stars > 0),
  status text not null default 'created' check (status in ('created','paid','completed','refunded','expired')),
  telegram_charge_id text unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  paid_at timestamptz,
  completed_at timestamptz,
  refunded_at timestamptz
);
alter table public.withdraw_intents add column if not exists gift_snapshot jsonb;
alter table public.withdraw_intents add column if not exists referral_credited_at timestamptz;
alter table public.withdraw_intents drop constraint if exists withdraw_intents_status_check;
alter table public.withdraw_intents add constraint withdraw_intents_status_check
  check (status in ('created','paid','transferring','completed','refunded','expired'));
create index if not exists withdraw_intents_user_idx on public.withdraw_intents(user_id, created_at desc);

create table if not exists public.ton_deposit_intents (
  id uuid primary key,
  user_id bigint not null,
  wallet_address text not null,
  destination_address text not null,
  amount_nano numeric(30,0) not null check (amount_nano > 0),
  stars_amount integer not null check (stars_amount > 0),
  status text not null default 'created' check (status in ('created','credited','expired')),
  tx_hash text unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  credited_at timestamptz
);
create index if not exists ton_deposit_intents_user_idx on public.ton_deposit_intents(user_id, created_at desc);

create table if not exists public.relayer_gift_receipts (
  msg_id bigint primary key,
  user_id bigint not null,
  gift_id text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.crash_state (
  id smallint primary key check (id = 1),
  round_id bigint not null,
  phase text not null check (phase in ('countdown','live','ended')),
  countdown_ends_at timestamptz not null,
  live_start_at timestamptz,
  crash_at timestamptz,
  crash_multiplier double precision not null,
  next_round_at timestamptz,
  growth_ms integer not null default 8000,
  history jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.crash_bets (
  round_id bigint not null,
  user_id bigint not null,
  first_name text,
  photo_url text,
  amount integer not null check (amount > 0),
  placed_at timestamptz not null default now(),
  cashed_out boolean not null default false,
  payout integer not null default 0,
  cashed_out_at timestamptz,
  awarded_gift jsonb,
  primary key (round_id, user_id)
);
create index if not exists crash_bets_round_idx on public.crash_bets(round_id, placed_at);

-- 53-bit cryptographically random unit interval [0,1).
create or replace function public.secure_random_unit()
returns double precision
language plpgsql
volatile
as $$
declare
  b bytea := gen_random_bytes(8);
  n numeric := 0;
  i integer;
begin
  for i in 0..7 loop
    n := n * 256 + get_byte(b, i);
  end loop;
  n := mod(n, 9007199254740992::numeric);
  return (n / 9007199254740992::numeric)::double precision;
end;
$$;

create or replace function public.sample_crash_target_secure()
returns double precision
language plpgsql
volatile
as $$
declare
  r double precision := public.secure_random_unit();
  x double precision;
begin
  if r < 0.55 then x := 1.01 + public.secure_random_unit() * 0.49;
  elsif r < 0.85 then x := 1.50 + public.secure_random_unit() * 1.00;
  elsif r < 0.95 then x := 2.50 + public.secure_random_unit() * 1.50;
  elsif r < 0.99 then x := 4.00 + public.secure_random_unit() * 3.00;
  else x := 7.00 + public.secure_random_unit() * 8.00;
  end if;
  return round(x::numeric, 2)::double precision;
end;
$$;

create or replace function public.crash_sync_state()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.crash_state%rowtype;
  now_ts timestamptz := clock_timestamp();
  target double precision;
  duration_ms integer;
  hist jsonb;
begin
  insert into public.crash_state(id, round_id, phase, countdown_ends_at, crash_multiplier, growth_ms, history)
  values (1, 1, 'countdown', now_ts + interval '10 seconds', public.sample_crash_target_secure(), 8000, '[]'::jsonb)
  on conflict (id) do nothing;

  select * into s from public.crash_state where id = 1 for update;

  loop
    if s.phase = 'countdown' and now_ts >= s.countdown_ends_at then
      s.phase := 'live';
      s.live_start_at := s.countdown_ends_at;
      duration_ms := greatest(400, round(s.growth_ms * ln(greatest(s.crash_multiplier, 1.01)))::integer);
      s.crash_at := s.live_start_at + (duration_ms::text || ' milliseconds')::interval;
      update public.crash_state set
        phase=s.phase, live_start_at=s.live_start_at, crash_at=s.crash_at, updated_at=now_ts
      where id=1;
    elsif s.phase = 'live' and s.crash_at is not null and now_ts >= s.crash_at then
      s.phase := 'ended';
      s.next_round_at := s.crash_at + interval '3 seconds';
      hist := jsonb_build_array(jsonb_build_object('roundId', s.round_id, 'multiplier', round(s.crash_multiplier::numeric,2))) || coalesce(s.history,'[]'::jsonb);
      s.history := (
        select coalesce(jsonb_agg(value), '[]'::jsonb)
        from (select value from jsonb_array_elements(hist) with ordinality t(value, ord) where ord <= 12 order by ord) q
      );
      update public.crash_state set
        phase=s.phase, next_round_at=s.next_round_at, history=s.history, updated_at=now_ts
      where id=1;
    elsif s.phase = 'ended' and s.next_round_at is not null and now_ts >= s.next_round_at then
      target := public.sample_crash_target_secure();
      s.round_id := s.round_id + 1;
      s.phase := 'countdown';
      s.countdown_ends_at := now_ts + interval '10 seconds';
      s.live_start_at := null;
      s.crash_at := null;
      s.crash_multiplier := target;
      s.next_round_at := null;
      update public.crash_state set
        round_id=s.round_id, phase=s.phase, countdown_ends_at=s.countdown_ends_at,
        live_start_at=null, crash_at=null, crash_multiplier=target, next_round_at=null,
        updated_at=now_ts
      where id=1;
    else
      exit;
    end if;
    select * into s from public.crash_state where id=1;
  end loop;

  return jsonb_build_object(
    'roundId', s.round_id,
    'phase', s.phase,
    'countdownEndsAt', extract(epoch from s.countdown_ends_at) * 1000,
    'liveStartAt', case when s.live_start_at is null then 0 else extract(epoch from s.live_start_at) * 1000 end,
    'crashAt', case when s.crash_at is null then 0 else extract(epoch from s.crash_at) * 1000 end,
    'crashMultiplier', s.crash_multiplier,
    'nextRoundAt', case when s.next_round_at is null then 0 else extract(epoch from s.next_round_at) * 1000 end,
    'growthMs', s.growth_ms,
    'history', s.history
  );
end;
$$;

create or replace function public.crash_place_bet(
  p_user_id bigint,
  p_first_name text,
  p_photo_url text,
  p_amount integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s jsonb;
  rid bigint;
  new_balance numeric;
begin
  if p_amount is null or p_amount <= 0 then raise exception 'Bad amount'; end if;
  s := public.crash_sync_state();
  if s->>'phase' <> 'countdown' then raise exception 'Round already started'; end if;
  rid := (s->>'roundId')::bigint;

  if exists(select 1 from public.crash_bets where round_id=rid and user_id=p_user_id) then
    raise exception 'Bet already placed';
  end if;
  if exists(select 1 from public.user_pending_prizes where user_id=p_user_id) then
    raise exception 'Resolve pending prize first';
  end if;

  select public.spend_balance(p_user_id, p_amount) into new_balance;
  insert into public.crash_bets(round_id,user_id,first_name,photo_url,amount)
  values(rid,p_user_id,p_first_name,p_photo_url,p_amount);

  return jsonb_build_object('roundId',rid,'newBalance',new_balance);
end;
$$;

create or replace function public.crash_settle_bet(
  p_user_id bigint,
  p_round_id bigint,
  p_awarded_gift jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.crash_state%rowtype;
  b public.crash_bets%rowtype;
  now_ts timestamptz := clock_timestamp();
  mult double precision;
  pay integer;
  new_balance numeric;
  gift_id text;
  gift_name text;
  gift_image text;
begin
  perform public.crash_sync_state();
  select * into s from public.crash_state where id=1 for update;
  if s.round_id <> p_round_id or s.phase <> 'live' or s.crash_at is null or now_ts >= s.crash_at then
    raise exception 'Round is not live';
  end if;

  select * into b from public.crash_bets where round_id=p_round_id and user_id=p_user_id for update;
  if not found then raise exception 'No active bet'; end if;
  if b.cashed_out then raise exception 'Already cashed out'; end if;

  mult := exp(greatest(0, extract(epoch from (now_ts - s.live_start_at)) * 1000) / s.growth_ms);
  mult := least(mult, s.crash_multiplier);
  pay := greatest(0, floor(b.amount * mult)::integer);

  update public.crash_bets set cashed_out=true,payout=pay,cashed_out_at=now_ts,awarded_gift=p_awarded_gift
  where round_id=p_round_id and user_id=p_user_id;

  if p_awarded_gift is not null and pay > 0 then
    gift_id := coalesce(p_awarded_gift->>'id', p_awarded_gift->>'giftId');
    gift_name := p_awarded_gift->>'name';
    gift_image := p_awarded_gift->>'image';
    if gift_id is null or gift_name is null or gift_image is null then raise exception 'Bad awarded gift'; end if;
    delete from public.user_pending_prizes where user_id=p_user_id;
    insert into public.user_pending_prizes(user_id,gift_id,gift_name,gift_price,gift_image,created_at)
    values(p_user_id,gift_id,gift_name,pay,gift_image,now_ts);
    select balance into new_balance from public.users where id=p_user_id;
  elsif pay > 0 then
    select public.add_win_balance(p_user_id, pay) into new_balance;
  else
    select balance into new_balance from public.users where id=p_user_id;
  end if;

  return jsonb_build_object('payout',pay,'newBalance',coalesce(new_balance,0));
end;
$$;

create or replace function public.link_signed_tg_username(p_user_id bigint, p_username text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare uname text := lower(regexp_replace(trim(coalesce(p_username,'')), '^@', ''));
begin
  if p_user_id is null or p_user_id <= 0 or uname = '' then raise exception 'Bad Telegram identity'; end if;
  -- initData proves that this username currently belongs to p_user_id; update both sides atomically.
  delete from public.tg_username_links where user_id=p_user_id or username=uname;
  insert into public.tg_username_links(username,user_id,updated_at) values(uname,p_user_id,now());
  return jsonb_build_object('username',uname,'userId',p_user_id);
end;
$$;

create or replace function public.inventory_take_gift(p_user_id bigint, p_gift_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare g public.user_gifts%rowtype;
begin
  delete from public.user_gifts where user_id=p_user_id and id=p_gift_id returning * into g;
  if not found then raise exception 'Gift not found'; end if;
  return to_jsonb(g);
end;
$$;

create or replace function public.inventory_sell_gift(p_user_id bigint, p_gift_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare g public.user_gifts%rowtype; new_balance numeric;
begin
  delete from public.user_gifts where user_id=p_user_id and id=p_gift_id returning * into g;
  if not found then raise exception 'Gift not found'; end if;
  select public.add_win_balance(p_user_id, coalesce(g.gift_price,0)::integer) into new_balance;
  return jsonb_build_object('soldPrice',coalesce(g.gift_price,0),'newBalance',new_balance);
end;
$$;

create or replace function public.inventory_sell_all(p_user_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare total numeric := 0; cnt integer := 0; new_balance numeric;
begin
  with d as (
    delete from public.user_gifts where user_id=p_user_id returning gift_price
  ) select coalesce(sum(gift_price),0), count(*) into total,cnt from d;
  if total > 0 then select public.add_win_balance(p_user_id,total::integer) into new_balance;
  else select balance into new_balance from public.users where id=p_user_id; end if;
  return jsonb_build_object('soldCount',cnt,'soldTotal',total,'newBalance',coalesce(new_balance,0));
end;
$$;

create or replace function public.pending_prize_take(p_user_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare p public.user_pending_prizes%rowtype;
begin
  delete from public.user_pending_prizes where user_id=p_user_id returning * into p;
  if not found then return null; end if;
  return to_jsonb(p);
end;
$$;

create or replace function public.pending_prize_resolve(p_user_id bigint, p_action text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare p public.user_pending_prizes%rowtype; g public.user_gifts%rowtype; new_balance numeric;
begin
  if p_action not in ('sell','claim') then raise exception 'Bad action'; end if;
  delete from public.user_pending_prizes where user_id=p_user_id returning * into p;
  if not found then raise exception 'Prize not found'; end if;

  if p_action='sell' then
    select public.add_win_balance(p_user_id,coalesce(p.gift_price,0)::integer) into new_balance;
    return jsonb_build_object('prize',to_jsonb(p),'newBalance',new_balance,'claimedGift',null);
  end if;

  insert into public.user_gifts(user_id,gift_id,gift_name,gift_price,gift_image,withdraw_available_at,created_at)
  values(p_user_id,p.gift_id,p.gift_name,p.gift_price,p.gift_image,now()+interval '20 minutes',now())
  returning * into g;
  select balance into new_balance from public.users where id=p_user_id;
  return jsonb_build_object('prize',to_jsonb(p),'newBalance',coalesce(new_balance,0),'claimedGift',to_jsonb(g));
end;
$$;

create or replace function public.inventory_upgrade_apply(
  p_user_id bigint,
  p_source_gift_id bigint,
  p_is_win boolean,
  p_target jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare src public.user_gifts%rowtype; won public.user_gifts%rowtype;
begin
  delete from public.user_gifts where user_id=p_user_id and id=p_source_gift_id returning * into src;
  if not found then raise exception 'Source gift not found'; end if;
  if p_is_win then
    insert into public.user_gifts(user_id,gift_id,gift_name,gift_price,gift_image,withdraw_available_at,created_at)
    values(p_user_id,p_target->>'id',p_target->>'name',(p_target->>'price')::numeric,p_target->>'image',now()+interval '20 minutes',now())
    returning * into won;
  end if;
  return jsonb_build_object('sourceGift',to_jsonb(src),'wonGift',case when p_is_win then to_jsonb(won) else null end);
end;
$$;

create or replace function public.inventory_craft_apply(
  p_user_id bigint,
  p_gift_ids bigint[],
  p_reward jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare selected_count integer; consumed jsonb; won public.user_gifts%rowtype;
begin
  with d as (
    delete from public.user_gifts where user_id=p_user_id and id=any(p_gift_ids) returning *
  ) select count(*), coalesce(jsonb_agg(to_jsonb(d)),'[]'::jsonb) into selected_count, consumed from d;
  if selected_count <> cardinality(p_gift_ids) then raise exception 'Some gifts were not found'; end if;

  insert into public.user_gifts(user_id,gift_id,gift_name,gift_price,gift_image,withdraw_available_at,created_at)
  values(p_user_id,p_reward->>'id',p_reward->>'name',(p_reward->>'price')::numeric,p_reward->>'image',now()+interval '20 minutes',now())
  returning * into won;
  return jsonb_build_object('consumed',consumed,'wonGift',to_jsonb(won));
end;
$$;

create or replace function public.withdraw_claim_for_transfer(p_intent_id uuid, p_user_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare w public.withdraw_intents%rowtype; g public.user_gifts%rowtype;
begin
  select * into w from public.withdraw_intents where id=p_intent_id and user_id=p_user_id for update;
  if not found then raise exception 'Withdraw intent not found'; end if;
  if w.status='completed' then return w.gift_snapshot; end if;
  if w.status='transferring' then
    if w.gift_snapshot is null then raise exception 'Transfer snapshot missing'; end if;
    return w.gift_snapshot;
  end if;
  if w.status <> 'paid' then raise exception 'Withdraw intent is not paid'; end if;

  delete from public.user_gifts where user_id=p_user_id and id=w.gift_db_id returning * into g;
  if not found then raise exception 'Gift not found'; end if;
  if g.withdraw_available_at is not null and g.withdraw_available_at > now() then
    raise exception 'Gift local hold is active';
  end if;
  if g.tg_msg_id is null and nullif(g.tg_slug,'') is null then
    raise exception 'Exact Telegram gift reference is missing';
  end if;
  if g.tg_is_unique is false then raise exception 'Gift is not unique'; end if;

  update public.withdraw_intents
  set status='transferring',gift_snapshot=to_jsonb(g)
  where id=p_intent_id;
  return to_jsonb(g);
end;
$$;

create or replace function public.withdraw_restore_transfer(p_intent_id uuid, p_user_id bigint)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare w public.withdraw_intents%rowtype; j jsonb;
begin
  select * into w from public.withdraw_intents where id=p_intent_id and user_id=p_user_id for update;
  if not found then raise exception 'Withdraw intent not found'; end if;
  if w.status='paid' then return true; end if;
  if w.status <> 'transferring' or w.gift_snapshot is null then raise exception 'Withdraw intent is not transferring'; end if;
  j := w.gift_snapshot;
  insert into public.user_gifts(
    id,user_id,gift_id,gift_name,gift_price,gift_image,withdraw_available_at,tg_msg_id,tg_slug,tg_is_unique,created_at
  ) values (
    (j->>'id')::bigint,(j->>'user_id')::bigint,j->>'gift_id',j->>'gift_name',
    coalesce((j->>'gift_price')::numeric,0),coalesce(j->>'gift_image',''),
    nullif(j->>'withdraw_available_at','')::timestamptz,
    nullif(j->>'tg_msg_id','')::bigint,nullif(j->>'tg_slug',''),
    case when j ? 'tg_is_unique' and j->>'tg_is_unique' <> '' then (j->>'tg_is_unique')::boolean else null end,
    coalesce(nullif(j->>'created_at','')::timestamptz,now())
  ) on conflict (id) do nothing;
  update public.withdraw_intents set status='paid' where id=p_intent_id;
  return true;
end;
$$;

create or replace function public.withdraw_mark_completed(p_intent_id uuid, p_user_id bigint)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare w public.withdraw_intents%rowtype;
begin
  select * into w from public.withdraw_intents where id=p_intent_id and user_id=p_user_id for update;
  if not found or w.status not in ('transferring','completed') then
    raise exception 'Withdraw intent cannot be completed';
  end if;
  if w.status='transferring' then
    update public.withdraw_intents
    set status='completed',completed_at=coalesce(completed_at,now())
    where id=p_intent_id;
  end if;
  if w.referral_credited_at is null then
    perform public.credit_referral_for_deposit(p_user_id,w.fee_stars);
    update public.withdraw_intents set referral_credited_at=now() where id=p_intent_id;
  end if;
  return true;
end;
$$;

create or replace function public.promo_redeem_atomic(
  p_user_id bigint,
  p_code text,
  p_reward_gift jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  pr public.promo_codes%rowtype;
  used integer := 0;
  reward_stars integer := 0;
  g public.user_gifts%rowtype;
  new_balance numeric;
  reward_id text;
begin
  select * into pr
  from public.promo_codes
  where lower(code)=lower(trim(coalesce(p_code,''))) and active is true
  order by code
  limit 1
  for update;
  if not found then raise exception 'Promo not found'; end if;

  select count(*) into used from public.manual_promo_redemptions
  where user_id=p_user_id and code=pr.code;
  if used >= greatest(1,coalesce(pr.max_uses_per_user,1)) then
    raise exception 'Promo already activated / limit reached';
  end if;

  if pr.reward_gift_id is not null then
    reward_id := coalesce(p_reward_gift->>'id',p_reward_gift->>'giftId');
    if p_reward_gift is null or reward_id is distinct from pr.reward_gift_id then
      raise exception 'Promo gift mismatch';
    end if;
  end if;

  insert into public.manual_promo_redemptions(user_id,code,redeemed_at)
  values(p_user_id,pr.code,now());

  if pr.reward_gift_id is not null then
    insert into public.user_gifts(user_id,gift_id,gift_name,gift_price,gift_image,withdraw_available_at,created_at)
    values(
      p_user_id, reward_id, p_reward_gift->>'name',
      greatest(0,floor(coalesce((p_reward_gift->>'price')::numeric,0))),
      coalesce(p_reward_gift->>'image',''), now()+interval '20 minutes', now()
    ) returning * into g;
    return jsonb_build_object('reward',0,'gift',to_jsonb(g));
  end if;

  reward_stars := greatest(0,floor(coalesce(pr.reward,0))::integer);
  if reward_stars <= 0 then raise exception 'Promo reward is invalid'; end if;
  select public.balance_add(p_user_id,reward_stars) into new_balance;
  return jsonb_build_object('reward',reward_stars,'balance',coalesce(new_balance,0),'gift',null);
end;
$$;

create or replace function public.admin_adjust_balance(p_user_id bigint, p_delta integer)
returns numeric
language plpgsql
security definer
set search_path=public
as $$
declare current_balance numeric; new_balance numeric;
begin
  if p_user_id is null or p_user_id <= 0 or p_delta is null or p_delta = 0 then
    raise exception 'Bad balance adjustment';
  end if;
  select balance into current_balance from public.users where id=p_user_id for update;
  if not found then raise exception 'User not found'; end if;
  new_balance := greatest(0,coalesce(current_balance,0)+p_delta);
  update public.users set balance=new_balance,updated_at=now() where id=p_user_id;
  return new_balance;
end;
$$;

create or replace function public.apply_telegram_star_payment(
  p_charge_id text,
  p_provider_charge_id text,
  p_invoice_id uuid,
  p_user_id bigint,
  p_amount integer,
  p_currency text,
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare inserted boolean := false; rc integer := 0; new_balance numeric;
begin
  if p_currency <> 'XTR' then raise exception 'Bad currency'; end if;
  if p_amount <= 0 then raise exception 'Bad amount'; end if;

  insert into public.payment_receipts(telegram_charge_id,provider_charge_id,invoice_id,user_id,kind,amount,currency,payload)
  values(p_charge_id,p_provider_charge_id,p_invoice_id,p_user_id,'deposit',p_amount,p_currency,p_payload)
  on conflict do nothing;
  get diagnostics rc = row_count;
  inserted := rc > 0;

  if inserted then
    select public.balance_add(p_user_id,p_amount) into new_balance;
    perform public.credit_referral_for_deposit(p_user_id,p_amount);
  else
    if not exists (
      select 1 from public.payment_receipts
      where kind='deposit' and user_id=p_user_id and amount=p_amount and currency=p_currency
        and (telegram_charge_id=p_charge_id or invoice_id=p_invoice_id)
    ) then
      raise exception 'Conflicting payment receipt';
    end if;
    select balance into new_balance from public.users where id=p_user_id;
  end if;
  return jsonb_build_object('applied',inserted,'balance',coalesce(new_balance,0));
end;
$$;

create or replace function public.apply_withdraw_fee_payment(
  p_charge_id text,
  p_provider_charge_id text,
  p_intent_id uuid,
  p_user_id bigint,
  p_amount integer,
  p_currency text,
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare w public.withdraw_intents%rowtype; inserted boolean := false; rc integer := 0;
begin
  select * into w from public.withdraw_intents where id=p_intent_id and user_id=p_user_id for update;
  if not found then raise exception 'Withdraw intent not found'; end if;
  if w.expires_at < now() and w.status='created' then
    update public.withdraw_intents set status='expired' where id=p_intent_id;
    raise exception 'Withdraw intent expired';
  end if;
  if p_currency <> 'XTR' or p_amount <> w.fee_stars then raise exception 'Payment mismatch'; end if;

  if w.status in ('paid','transferring','completed','refunded') then
    if w.telegram_charge_id = p_charge_id then
      return jsonb_build_object('applied',false,'status',w.status);
    end if;
    raise exception 'Withdraw intent already paid';
  end if;
  if w.status <> 'created' then raise exception 'Withdraw intent is not payable'; end if;

  insert into public.payment_receipts(telegram_charge_id,provider_charge_id,withdraw_intent_id,user_id,kind,amount,currency,payload)
  values(p_charge_id,p_provider_charge_id,p_intent_id,p_user_id,'withdraw',p_amount,p_currency,p_payload)
  on conflict do nothing;
  get diagnostics rc = row_count;
  inserted := rc > 0;

  if inserted then
    update public.withdraw_intents set status='paid',telegram_charge_id=p_charge_id,paid_at=now() where id=p_intent_id;
  else
    if not exists (
      select 1 from public.payment_receipts
      where kind='withdraw' and withdraw_intent_id=p_intent_id and telegram_charge_id=p_charge_id
        and user_id=p_user_id and amount=p_amount and currency=p_currency
    ) then
      raise exception 'Conflicting withdraw payment receipt';
    end if;
  end if;
  return jsonb_build_object('applied',inserted,'status',(select status from public.withdraw_intents where id=p_intent_id));
end;
$$;

create or replace function public.apply_ton_deposit(p_intent_id uuid, p_tx_hash text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare i public.ton_deposit_intents%rowtype; new_balance numeric;
begin
  select * into i from public.ton_deposit_intents where id=p_intent_id for update;
  if not found then raise exception 'TON intent not found'; end if;
  if i.status='credited' then
    select balance into new_balance from public.users where id=i.user_id;
    return jsonb_build_object('applied',false,'balance',coalesce(new_balance,0),'amount',i.stars_amount);
  end if;
  if i.status <> 'created' then raise exception 'TON intent is not creditable'; end if;
  if i.expires_at < now() - interval '2 minutes' then raise exception 'TON intent expired'; end if;
  if exists(select 1 from public.ton_deposit_intents where tx_hash=p_tx_hash and id<>p_intent_id) then
    raise exception 'TON transaction already used';
  end if;

  update public.ton_deposit_intents set status='credited',tx_hash=p_tx_hash,credited_at=now() where id=p_intent_id;
  select public.balance_add(i.user_id,i.stars_amount) into new_balance;
  perform public.credit_referral_for_deposit(i.user_id,i.stars_amount);
  return jsonb_build_object('applied',true,'balance',coalesce(new_balance,0),'amount',i.stars_amount);
end;
$$;

create or replace function public.credit_relayer_gift(
  p_msg_id bigint,
  p_user_id bigint,
  p_gift jsonb,
  p_slug text,
  p_is_unique boolean
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare rc integer := 0; g public.user_gifts%rowtype; price integer;
begin
  if p_msg_id is null or p_msg_id <= 0 then raise exception 'msg_id required'; end if;
  insert into public.relayer_gift_receipts(msg_id,user_id,gift_id)
  values(p_msg_id,p_user_id,coalesce(p_gift->>'id',p_gift->>'giftId'))
  on conflict (msg_id) do nothing;
  get diagnostics rc = row_count;
  if rc = 0 then return jsonb_build_object('duplicate',true); end if;

  price := greatest(0, floor(coalesce((p_gift->>'price')::numeric,0))::integer);
  insert into public.user_gifts(user_id,gift_id,gift_name,gift_price,gift_image,withdraw_available_at,tg_msg_id,tg_slug,tg_is_unique,created_at)
  values(p_user_id,p_gift->>'id',p_gift->>'name',price,p_gift->>'image',now()+interval '20 minutes',p_msg_id,p_slug,p_is_unique,now())
  returning * into g;

  if price > 0 then
    update public.users set total_deposited=coalesce(total_deposited,0)+price,updated_at=now() where id=p_user_id;
    perform public.credit_referral_for_deposit(p_user_id,price);
  end if;
  return jsonb_build_object('duplicate',false,'gift',to_jsonb(g));
end;
$$;

-- RPCs are intended for the trusted backend (service-role key), not direct browser use.
revoke all on function public.crash_sync_state() from public, anon, authenticated;
revoke all on function public.crash_place_bet(bigint,text,text,integer) from public, anon, authenticated;
revoke all on function public.crash_settle_bet(bigint,bigint,jsonb) from public, anon, authenticated;
revoke all on function public.link_signed_tg_username(bigint,text) from public, anon, authenticated;
revoke all on function public.inventory_take_gift(bigint,bigint) from public, anon, authenticated;
revoke all on function public.inventory_sell_gift(bigint,bigint) from public, anon, authenticated;
revoke all on function public.inventory_sell_all(bigint) from public, anon, authenticated;
revoke all on function public.pending_prize_take(bigint) from public, anon, authenticated;
revoke all on function public.pending_prize_resolve(bigint,text) from public, anon, authenticated;
revoke all on function public.inventory_upgrade_apply(bigint,bigint,boolean,jsonb) from public, anon, authenticated;
revoke all on function public.inventory_craft_apply(bigint,bigint[],jsonb) from public, anon, authenticated;
revoke all on function public.withdraw_claim_for_transfer(uuid,bigint) from public, anon, authenticated;
revoke all on function public.withdraw_restore_transfer(uuid,bigint) from public, anon, authenticated;
revoke all on function public.withdraw_mark_completed(uuid,bigint) from public, anon, authenticated;
revoke all on function public.promo_redeem_atomic(bigint,text,jsonb) from public, anon, authenticated;
revoke all on function public.admin_adjust_balance(bigint,integer) from public, anon, authenticated;
revoke all on function public.apply_telegram_star_payment(text,text,uuid,bigint,integer,text,jsonb) from public, anon, authenticated;
revoke all on function public.apply_withdraw_fee_payment(text,text,uuid,bigint,integer,text,jsonb) from public, anon, authenticated;
revoke all on function public.apply_ton_deposit(uuid,text) from public, anon, authenticated;
revoke all on function public.credit_relayer_gift(bigint,bigint,jsonb,text,boolean) from public, anon, authenticated;


-- Explicitly keep the hardened RPCs callable by the server-side Supabase service-role key.
grant execute on function public.crash_sync_state() to service_role;
grant execute on function public.crash_place_bet(bigint,text,text,integer) to service_role;
grant execute on function public.crash_settle_bet(bigint,bigint,jsonb) to service_role;
grant execute on function public.link_signed_tg_username(bigint,text) to service_role;
grant execute on function public.inventory_take_gift(bigint,bigint) to service_role;
grant execute on function public.inventory_sell_gift(bigint,bigint) to service_role;
grant execute on function public.inventory_sell_all(bigint) to service_role;
grant execute on function public.pending_prize_take(bigint) to service_role;
grant execute on function public.pending_prize_resolve(bigint,text) to service_role;
grant execute on function public.inventory_upgrade_apply(bigint,bigint,boolean,jsonb) to service_role;
grant execute on function public.inventory_craft_apply(bigint,bigint[],jsonb) to service_role;
grant execute on function public.withdraw_claim_for_transfer(uuid,bigint) to service_role;
grant execute on function public.withdraw_restore_transfer(uuid,bigint) to service_role;
grant execute on function public.withdraw_mark_completed(uuid,bigint) to service_role;
grant execute on function public.promo_redeem_atomic(bigint,text,jsonb) to service_role;
grant execute on function public.admin_adjust_balance(bigint,integer) to service_role;
grant execute on function public.apply_telegram_star_payment(text,text,uuid,bigint,integer,text,jsonb) to service_role;
grant execute on function public.apply_withdraw_fee_payment(text,text,uuid,bigint,integer,text,jsonb) to service_role;
grant execute on function public.apply_ton_deposit(uuid,text) to service_role;
grant execute on function public.credit_relayer_gift(bigint,bigint,jsonb,text,boolean) to service_role;
grant select, insert, update, delete on public.payment_receipts, public.withdraw_intents,
  public.ton_deposit_intents, public.relayer_gift_receipts, public.crash_state, public.crash_bets to service_role;

-- Browser clients must not access financial/inventory state directly. All access goes through server.js.
alter table public.promo_codes enable row level security;
alter table public.manual_promo_redemptions enable row level security;
alter table public.user_gifts enable row level security;
alter table public.user_pending_prizes enable row level security;
alter table public.tg_username_links enable row level security;
alter table public.payment_receipts enable row level security;
alter table public.withdraw_intents enable row level security;
alter table public.ton_deposit_intents enable row level security;
alter table public.relayer_gift_receipts enable row level security;
alter table public.crash_state enable row level security;
alter table public.crash_bets enable row level security;

revoke all on table public.promo_codes, public.manual_promo_redemptions, public.user_gifts, public.user_pending_prizes, public.tg_username_links,
  public.payment_receipts, public.withdraw_intents, public.ton_deposit_intents,
  public.relayer_gift_receipts, public.crash_state, public.crash_bets from anon, authenticated;

grant select, insert, update, delete on public.promo_codes, public.manual_promo_redemptions, public.user_gifts, public.user_pending_prizes, public.tg_username_links,
  public.payment_receipts, public.withdraw_intents, public.ton_deposit_intents,
  public.relayer_gift_receipts, public.crash_state, public.crash_bets to service_role;

-- Identity-backed inserts by service-role RPCs may use existing/new sequences.
grant usage, select on all sequences in schema public to service_role;
